### PR TITLE
metric-name was invalid, thus rejected by prometheus

### PR DESCRIPTION
**Pull request by pvdh**
Graphs are rejected silently, since it is "register" instead of "mustRegister".
Replacing each occurence of "-" by "_" should be good enough.

### CODE REVIEW

**Comment by beorn7** [comment]
Thanks for the fix.

However, this junkyard org is not the right location to maintain the code. Either we resurrect it into the prometheus org, or you fork it and maintain it under your own org. (We can then point to your fork in the general Prometheus docs.)

However (2nd level however :), I'm sure there was a reason why we moved the Munin exporter into the junkyard. @juliusv do you remember the rationale? Is the functionality available somewhere else? Node exporter module somewhere?

**Comment by beorn7** [comment]
We had a little discussion in the group of core maintainers.

Our expectation is that there will be more and more exporters of any kind. It doesn't make sense to have them all in the Prometheus github org. To prevent an infinite blow-up of the org, we will only add new repositories to the Prometheus github org that are core components of the ecosystem. Special purpose exporters are encouraged to be maintained outside of the Prometheus github org.

In this case, we would ask you to fork this repo to your own org and maintain it there. We will add a hint here that the canonical version is your fork, and we will link it from the documentation site in the list of "inofficial" exporters (we might need to find a better name than "inofficial" for that - more like "maintained by external contributors" or something).

Sounds good?

**Comment by pvdh** [comment]
Oh, please, come on. You've seen ALL the coding I ever did in go and I got less then two hours experience in using prometheus.
Still, my updated version is probably the best version of munin_exporter ever. ;-)
I can't promise to really maintain it for an extended period and might try to hand it over to the first one offering a pull request, but that seems to be more than we have right now. Would be a schame if the munin-plugins could not feed to prometheus.
Deal?

**Comment by beorn7** [comment]
Deal? I mean, are you alright with blessing your fork as the most current version of the munin_exporter?
In that case, I'd add a notice in the README pointing to your fork.

**Comment by juliusv** [comment]
In that case I'd even recommend un-forking it and just copying it manually to your new repo, since otherwise GitHub will forever track this fork relationship and people could think this one here is the "main" one.

**Comment by pvdh** [comment]
OK, will unfork and start fresh. Last question: munin_exporter uses the Apache 2.0 license?

**Comment by juliusv** [comment]
See, it doesn't even have a license yet - /cc @discordianfish who initially wrote it to give you clearance to just take it and do whatever you feel with it :)

**Comment by discordianfish** [comment]
Fine with me, but I wrote this as SoundCloud employee so AFAIK the right are at SoundCloud.

**Comment by juliusv** [comment]
ZOMG zee legal stuffs.

Hmm, ok - @pvdh Honestly, I think it should be fine for you to just take it and put it under any license you like. I don't think anyone will ever care for this particular small piece of abandoned source code :)

**Comment by discordianfish** [comment]
:+1:

**Comment by beorn7** [comment]
To avoid any kind of complications, I'd go with MIT (the SoundCloud standard license for OSS) or with Apache 2.0 (the license approved for Prometheus).

**Comment by pvdh** [comment]
I'll take munin_exporter under MIT license. Currently I've been busy meeting a deadline, but will setup a new repository and some docs at the weekend.

**Comment by pvdh** [comment]
I started all over at https://github.com/pvdh/munin_exporter-temp
After adding labels to the metrics I'm very happy.

**Comment by discordianfish** [comment]
@pvdh So you're planning to replace munin_exporter by munin_exporter-temp? Sounds good, I like that munin_exporter-temp persists the old commits. If you don't want the "forked from" link, you can simply create a new empty repo and push your code to it (vs using the fork button).

**Comment by pvdh** [comment]
@discordianfish No, I renamed the fork of munin_exporter to munin_expoter-temp and started fresh with a new project munin_exporter, as suggested by @juliusv . At least that's what I think, since I'm used to subversion and lack expierience with git. Would there have been a better way? Still early enough to undo it, I guess.

**Comment by discordianfish** [comment]
@pvdh The IMO best way would be to first backup your changes, then run the following:

```
git clone https://github.com/prometheus-junkyard/munin_exporter.git
cd munin_exporter/
git remote remove origin
git remote add origin git@github.com:pvdh/munin_exporter.git
git push origin master -f
```
I haven't tested it, but this should overwrite your current munin_exporter with what is in this repo but without the "forked from" link. After that, you can add your changes back.

**Comment by beorn7** [comment]
@pvdh I guess now that you have already set everything up and announced the repo, the discussion is more or less academic. No change required. I'll add a reference to your new repo from the docs ASAP.

Thanks.

**Comment by pvdh** [comment]
It's not that much effort to redo it, and probably necessary git training.
;-) I might redo it at the weekend (if nobody forks ;-)), but I wouldn't
change the name, so any link would be stable.

On Wed, Jun 17, 2015 at 12:23 AM, Björn Rabenstein <notifications@github.com

> wrote:
> 
> @pvdh https://github.com/pvdh I guess now that you have already set
> everything up and announced the repo, the discussion is more or less
> academic. No change required. I'll add a reference to your new repo from
> the docs ASAP.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/prometheus-junkyard/munin_exporter/pull/6#issuecomment-112587213
> .

## 

CU,
   Patrick.

**Comment by juliusv** [comment]
Hmm, I wouldn't recommend rewriting the master-branch history of a
published repo, even if nobody forked it yet. Anyone who has cloned will
also get errors next time they pull.

**Pull request closed without merging**
